#ifndef __MSPI_H
#define __MSPI_H
#include "stm32f10x.h"

// 时钟 D0
#define OLED_SPI_CLK_GPIO GPIOB
#define OLED_SPI_CLK_PIN GPIO_Pin_11
#define OLED_SPI_CLK_PIN_ID 11
#define OLED_SPI_CLK_PIN_RCC RCC_APB2Periph_GPIOB

// 数据 D1
#define OLED_SPI_DIN_GPIO GPIOB
#define OLED_SPI_DIN_PIN GPIO_Pin_10
#define OLED_SPI_DIN_PIN_ID 10
#define OLED_SPI_DIN_PIN_RCC RCC_APB2Periph_GPIOB

// 重置 RES
#define OLED_SPI_RES_GPIO GPIOB
#define OLED_SPI_RES_PIN GPIO_Pin_1
#define OLED_SPI_RES_PIN_ID 1
#define OLED_SPI_RES_PIN_RCC RCC_APB2Periph_GPIOB

// 命令 DC
#define OLED_SPI_DC_GPIO GPIOB
#define OLED_SPI_DC_PIN GPIO_Pin_0
#define OLED_SPI_DC_PIN_ID 0
#define OLED_SPI_DC_PIN_RCC RCC_APB2Periph_GPIOB

// 片选 CS
#define OLED_SPI_CS_GPIO GPIOA
#define OLED_SPI_CS_PIN GPIO_Pin_7
#define OLED_SPI_CS_PIN_ID 7
#define OLED_SPI_CS_PIN_RCC RCC_APB2Periph_GPIOA

#define OLED_SPI_CLK_H (OLED_SPI_CLK_GPIO->BSRR = OLED_SPI_CLK_PIN)
#define OLED_SPI_CLK_L (OLED_SPI_CLK_GPIO->BRR = OLED_SPI_CLK_PIN)
#define OLED_SPI_DIN_H (OLED_SPI_DIN_GPIO->BSRR = OLED_SPI_DIN_PIN)
#define OLED_SPI_DIN_L (OLED_SPI_DIN_GPIO->BRR = OLED_SPI_DIN_PIN)
#define OLED_SPI_RES_H (OLED_SPI_RES_GPIO->BSRR = OLED_SPI_RES_PIN)
#define OLED_SPI_RES_L (OLED_SPI_RES_GPIO->BRR = OLED_SPI_RES_PIN)
#define OLED_SPI_DC_H (OLED_SPI_DC_GPIO->BSRR = OLED_SPI_DC_PIN)
#define OLED_SPI_DC_L (OLED_SPI_DC_GPIO->BRR = OLED_SPI_DC_PIN)
#define OLED_SPI_CS_H (OLED_SPI_CS_GPIO->BSRR = OLED_SPI_CS_PIN)
#define OLED_SPI_CS_L (OLED_SPI_CS_GPIO->BRR = OLED_SPI_CS_PIN)

void OLED_SPI_GPIO_Init(void);
void OLED_SPI_Init(void);
void OLED_SPI_W_CMD(u8 cmd);
void OLED_SPI_W_DATA(u8 data);
void OLED_SPI_Set_Cursor(u8 x, u8 page);

void OLED_Display_On(void);
void OLED_Display_Off(void);

#endif
